### ISSUE TITLE
I found some issues

### ISSUE THREAD

**Issue by golles** [sintret/yii2-chat-adminlte#1]
ChatRoom.php line 63
Change:

```
$output .='';
```

To:

```
$output ='';
```

Please add a migration to create the table.

I have tablePrefix for my database tables but your extension does not use this prefix.

**Comment by golles** [comment]
I decided not to use this anymore as there are many issues with this

**Comment by sintret** [comment]
i just fixed my widget with the documentation too. 
i can not to use migration because i have no modul

**Comment by golles** [comment]
Thank you for the quick action, I retried it and still have some issues. Mostly can easily be fixed. 

Chat.php and ChatRoom.php have the same data() method, you should have it only once, and please fix the following problems in them:

Change Chat.php#68 (This throws an error as $output is not defined yet)

```
$output .= '';
```

To:

```
$output = '';
```

Change Chat.php#75 (The avatar is not published so it gived a 404)

```
$avatar = Yii::getAlias("@vendor/sintret/yii2-chat-adminlte/assets/img/avatar.png");
```

To:

```
$avatar = Yii::$app->assetManager->publish('@vendor/sintret/yii2-chat-adminlte/assets/img/avatar.png';)[1];
```

Change ChatRoom.php#88 (This throws an error as $output is not defined yet)

```
$output .= '';
```

To:

```
$output = '';
```

Change ChatRoom.php#95 (The avatar is not published so it gived a 404)

```
$avatar = Yii::getAlias("@vendor/sintret/yii2-chat-adminlte/assets/img/avatar.png");
```

To:

```
$avatar = Yii::$app->assetManager->publish('@vendor/sintret/yii2-chat-adminlte/assets/img/avatar.png';)[1];
```

Controller: 
I had to add this to my controller:

```
public $enableCsrfValidation = false;
```

I had to change the action like this:

```
public function actionChat() {
    if (!empty($_POST)) {
        echo \sintret\chat\ChatRoom::sendChat($_POST);
    }
}
```

As I get errors that message ($post['message']) is not defined.

In the docs the parsing of the widget is incomplete

```
<?= \sintret\chat\ChatRoom::widget(['url'=> \yii\helpers\Url::to(['/default/chat']), 'userModel'=>  \yii\web\User::className(), 'userField' => 'avatarImage']); ?>
```
